# Messages and copy mode.
set -g message-style "bg=#262626,fg=#D0D0D0"
set -g message-command-style "bg=#FF7EB6,fg=#161616,bold"
set -g mode-style "bg=#78A9FF,fg=#161616,bold"

# Popups.
set -g popup-style "bg=#131313,fg=#F2F2F2"
set -g popup-border-style "fg=#393939"

# Menus.
set -g menu-style "bg=#262626,fg=#D0D0D0"
set -g menu-selected-style "bg=#393939,fg=#3DDBD9,bold"
set -g menu-border-style "fg=#393939"
