# Pane borders.
set -g pane-border-status off
set -g pane-border-style "fg=#262626"
set -g pane-active-border-style "fg=#78A9FF"

# Pane number overlay.
set -g display-panes-colour "#525252"
set -g display-panes-active-colour "#3DDBD9"
