# Status bar layout.
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-justify left
set -g status-style "bg=#161616,fg=#D0D0D0"

# Left and right sections.
set -g status-left-length 0
set -g status-left ""

set -g status-right-length 120
set -g status-right '#{?client_prefix,#[fg=#161616#,bg=#FF7EB6#,bold] PREFIX ,}#[fg=#161616,bg=#42BE65,bold] #{b:pane_current_path} #[fg=#161616,bg=#3DDBD9,bold] #{pane_current_command} #[fg=#D0D0D0,bg=#262626] %H:%M '

# Window tabs.
set -g window-status-separator ""
set -g window-status-format '#[fg=#525252,bg=#393939] #I #[fg=#D0D0D0,bg=#262626] #W '
set -g window-status-current-format '#[fg=#161616,bg=#82CFFF,bold] #I #[fg=#161616,bg=#78A9FF,bold] #W '

set -g window-status-style "bg=#262626,fg=#525252"
set -g window-status-current-style "bg=#78A9FF,fg=#161616,bold"
set -g window-status-last-style "bg=#262626,fg=#82CFFF"
set -g window-status-activity-style "bg=#42BE65,fg=#161616,bold"
set -g window-status-bell-style "bg=#EE5396,fg=#161616,bold"
