# Window naming.
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

# Activity and bell behavior.
set -g monitor-activity on
set -g visual-activity off
set -g visual-bell off
